### ISSUE TITLE
ElasticSearch 1.7 crashes after doing a dry-run query

### ISSUE THREAD

**Issue by eddieantonio** [naturalness/partycrasher#25]
I have no idea why since this should be the same query as any other bucketing:

```
[2016-03-15 20:19:25,023][DEBUG][action.search.type       ] [Lord Pumpkin] All shards failed for phase: [query]
org.elasticsearch.action.NoShardAvailableActionException: [crashes][4] null
    at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.start(TransportSearchTypeAction.java:160)
    at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:62)
    at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:52)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
    at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:100)
    at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:43)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
    at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
    at org.elasticsearch.client.FilterClient.execute(FilterClient.java:66)
    at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.execute(BaseRestHandler.java:92)
    at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:338)
    at org.elasticsearch.rest.action.search.RestSearchAction.handleRequest(RestSearchAction.java:84)
    at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:53)
    at org.elasticsearch.rest.RestController.executeHandler(RestController.java:225)
    at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:170)
```

**Comment by eddieantonio** [comment]
Doing a cluster restart fixed this. For some reason.
